version: '3.3'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
volumes:
  my-db: